name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-linux-gcc:
    name: Linux-gcc
    runs-on: ubuntu-latest
    env:
      CFLAGS: -Werror
      CXXFLAGS: -Werror
      
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --user Jinja2>=2.7,<3.0
        python -m pip install --user markupsafe==2.0.1
    
    - name: Install dependecies
      working-directory: ${{runner.workspace}}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libegl1-mesa-dev
    
    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}
      
  build-linux-clang:
    name: Linux-clang
    runs-on: ubuntu-latest
    env:
      CFLAGS: -Werror
      CXXFLAGS: -Werror
      CC: clang
      CXX: clang++

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependecies
      working-directory: ${{runner.workspace}}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libegl1-mesa-dev
    
    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}
      
