name: MacOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-macos:
    name: MacOS
    runs-on: macos-latest
    env:
      CC: clang
      CXX: clang++
      CFLAGS: -Werror
      CXXFLAGS: -Werror

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --user -r requirements.txt
        
    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}
      
