
name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-win32:
    name: Win32
    runs-on: windows-latest
    env:
      CFLAGS: /WX
      CXXFLAGS: /WX

    steps:
    - uses: actions/checkout@v2
        
    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}
