
name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-win32:
    name: Win32
    runs-on: windows-latest
    env:
      CFLAGS: /WX
      CXXFLAGS: /WX

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --user Jinja2==2.11.3
        python -m pip install --user markupsafe==2.0.1
        
    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}
